version: '3.9'

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5434:5432
    volumes:
      - mystudy_pg_data:/var/lib/postgresql/data/

  api:
    build: ./backend
    ports:
      - '5000:5000'
    env_file:
      - docker.env
    depends_on:
      - db
    volumes:
      - ./backend:/backend
  # frontend:
  #   build: ./frontend
  #   ports:
  #     - '3000:3000'
  #   volumes:
  #     - ./frontend:frontend
  #     - /frontend/node_modules
  #   env_file:
  #     - docker.env

volumes:
  mystudy_pg_data:
