import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import { useState, useEffect } from 'react';
import styled from 'styled-components';
import LoginComponent from './components/LoginComponent';
import Timer from './components/Timer';

const Title = styled.span`
  font-size: 72px;
`;

const MainBody = styled.div`
  background-color: #D4D2A5;
  height: 100vh;
  width: 100vw;
  display: flex;
  justify-content: center;
`;

export default function Home() {
	const startingTime = 20;
	const [ hasStarted, setHasStarted ] = useState(false);
	const [ timeLeft, setTimeLeft ] = useState(startingTime);	//25 minute default

	const handleTimesUp = () => {
		console.log('hi');
	}

	useEffect(() => {
			if (timeLeft === 0) {
				handleTimesUp();
				return;
			}
			setTimeout(() => {
				setTimeLeft(timeLeft - 1);
			}, 1000);
		},
	), [ timeLeft, hasStarted ];

	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app"/>
				<link rel="icon" href="/favicon.ico"/>
			</Head>

			<MainBody>
				{/*<LoginComponent img={'/room.png'}></LoginComponent>*/}
				<Timer startingTime={startingTime} currentTime={timeLeft} icon={'/clock.svg'}></Timer>
			</MainBody>

		</div>
	);
}
