import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import styled from 'styled-components';
import LoginComponent from './components/LoginComponent';

const MainBody = styled.div`
  background: #D4D2A5;
  height: 100vh;
  width: 100vw;
  display: flex;
  justify-content: center;
`;

const Title = styled.span`
  font-size: 72px;
`;

export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app"/>
				<link rel="icon" href="/favicon.ico"/>
			</Head>

			<MainBody>
				{/*<LoginComponent img={'/room.png'}></LoginComponent>*/}
				<></>
			</MainBody>

		</div>
	);
}
